import * as cssLoader from "css-loader"
import * as lodash from "lodash"
import * as underscore from "underscore"
import * as vue from "vue"
import * as vueRouter from "vue-router"
import * as vueStyleLoader from "vue-style-loader"
import * as vueTemplateCompiler from "vue-template-compiler"
import * as react from "react"
